# Sketchup 표준 API 를 사용하기 위해 sketchup.rb 파일을 포함시킨다
require 'sketchup.rb'
Sketchup.send_action "showRubyPanel:"
# Plug-in이 실행될 때 메뉴를 추가.

UI.menu("PlugIns").add_item("Draw stair attributes") { 
	UI.messagebox("I'm about to draw spiral stairs!")
	
}


def draw_stairs
	radius = 200
	angle_interval = 3.14159 / 30.0
	stairs = 255  
	rise = 8  
	run = 12  
	width = 100  
	thickness = 3

	# 도형을 관리하는 모델 객체를 획득
	model = Sketchup.active_model  
	entities = model.entities  

  
# 계단 면 생성
pt1 = [0, 0, 0]  
pt2 = [9, 0, 0]  
pt3 = [9, 9, 0]  
pt4 = [0, 9, 0] 
	
		group = entities.add_group
		new_face = group.entities.add_face pt1, pt2, pt3, pt4  
			
		# 속성 설정
		create_if_nil = true 
		attrdict = group.attribute_dictionary "test_dict", create_if_nil 
		attrdict["attr_one"] = "one" 
		attrdict["attr_two"] = "two" # Gets an array of values 


		new_face.set_attribute "stair_parameter", "radius", radius
		new_face.set_attribute "stair_parameter", "width", width
		new_face.set_attribute "stair_parameter", "thickness", thickness

		attrdict = model.attribute_dictionaries['test_dict'] 
		attrdict.each { | key, value |   UI.messagebox key.to_s + '=' + value.to_s }
end